from enum import Enum


class SQL_CONSTS:
    class TablesNames(str, Enum):
        WOMEN_DETAILS = 'women_details'
        CHILD_DETAILS = 'children_details'

    class WOMEN_DETAILS_COLUMNS(str, Enum):
        IDENTIFIER = 'identifier'
        EMAIL = 'email'
        MEDICAL_PROVIDER_NAME = 'medical_provider_name'
        LAST_PERIOD_DATE = 'last_period_date'
        FULL_NAME = 'full_name'
        NUM_OF_PREGNENCY = 'num_of_pregnancy'
        BIRTHDAY = 'birthday'
        PASSWORD = 'password'
        FORGOT_PASSWORD_LINK_SECRET = 'forgot_password_link_secret'
        ULTRASOUND_1 = 'ultrasound_1'
        SISI_SHELIA = 'sisi_shelia'
        SHKIFUT_ORPIT = 'shkifut_orpit'
        SKIRAT_MARCHOT_MUKDEMET = 'skirat_marchot_mukdemet'
        HELBON_UBARI = 'helbon_ubari'
        DIKUR_MI_SHAFIR = 'dikur_mi_shafir'
        SKIRAT_MARCHOT_MEUCHERET = 'skirat_marchot_meucheret'
        HAMASAT_SUGARAR = 'hamasat_sugar'
        ULTRASOUND_2 = 'ultrasound_2'
        TARBIT_GBS = 'tabit_gbs'
        NITUR_UBARI = 'nitur_ubari'
        PRIMARY_KEY = f'{IDENTIFIER}'

    class CHILDREN_DETAILS(str, Enum):
        IDENTIFIER = 'identifier'
        MOTHER_ID = 'mother_id'
        CHILD_NAME = 'child_name'
        BIRTHDAY = 'birthday'
        TZHEVER_B_MANA_1 = 'tzhevet_b_mana_1'
        TZHEVER_B_MANA_2 = 'tzhevet_b_mana_2'
        TZHEVER_B_MANA_3 = 'tzhevet_b_mana_3'
        PALETZET_MANA_1 = 'paletzet_mana_1'
        PALETZET_MANA_2 = 'paletzet_mana_2'
        PALETZET_MANA_3 = 'paletzet_mana_3'
        PALETZET_MANA_4 = 'paletzet_mana_4'
        POLIO_1= 'polio_1'
        POLIO_2 = 'polio_2'
        HEMOFILOS_MANA_1 = 'hemofilos_mana_1'
        HEMOFILOS_MANA_2 = 'hemofilos_mana_2'
        HEMOFILOS_MANA_3 = 'hemofilos_mana_3'
        HEMOFILOS_MANA_4 = 'hemofilos_mana_4'
        PNOIMOKOK_MANA_1 = 'pnoimokok_nama_1'
        PNOIMOKOK_MANA_2 = 'pnoimokok_nama_2'
        PNOIMOKOK_MANA_3 = 'pnoimokok_nama_3'
        NEGIF_ROTA_MANA_1 = 'negif_rota_mana_1'
        NEGIF_ROTA_MANA_2 = 'negif_rota_mana_2'
        NEGIF_ROTA_MANA_3 = 'negif_rota_mana_3'
        HATZEVET_HAZERET_ADEMET_HABABUOT = 'hatzevet_hazeret_ademet_hababuot'
        TZHEVET_A_MANA_1 = 'tzhevet_a_mana_1'
        TZHEVET_A_MANA_2 = 'tzhevet_a_mana_2'
        PRIMARY_KEY = f'{IDENTIFIER}'
